spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springsecurity?UseSSL=false
    username: springstudent
    password: springstudent
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
          dialect: org.hibernate.dialect.MySQLDialect