INSERT INTO `student` (`student_name`) VALUES ('Neeme ');
INSERT INTO `student` (`student_name`) VALUES ('Christopher ');
INSERT INTO `student` (`student_name`) VALUES ('Kristina ');
INSERT INTO `student` (`student_name`) VALUES ('Susanna');
INSERT INTO `student` (`student_name`) VALUES ('Aleksander ');
INSERT INTO `student` (`student_name`) VALUES ('Karl');
INSERT INTO `student` (`student_name`) VALUES ('Joel ');
INSERT INTO `student` (`student_name`) VALUES ('Silver');
INSERT INTO `student` (`student_name`) VALUES ('Miquel');
INSERT INTO `student` (`student_name`) VALUES ('Kitaek ');
INSERT INTO `student` (`student_name`) VALUES ('Leonardo');
INSERT INTO `student` (`student_name`) VALUES ('Pedro Iglesias');
INSERT INTO `student` (`student_name`) VALUES ('Mikael ');
INSERT INTO `student` (`student_name`) VALUES ('Valentin ');

INSERT INTO `teacher` (`teacher_name`) VALUES ('Peter');
INSERT INTO `teacher` (`teacher_name`) VALUES ('Allan');
INSERT INTO `teacher` (`teacher_name`) VALUES ('Julia');
INSERT INTO `teacher` (`teacher_name`) VALUES ('Daniel');
INSERT INTO `teacher` (`teacher_name`) VALUES ('Catarine');
INSERT INTO `teacher` (`teacher_name`) VALUES ('Sophia');
INSERT INTO `teacher` (`teacher_name`) VALUES ('Lily');
INSERT INTO `teacher` (`teacher_name`) VALUES ('Natalie');
INSERT INTO `teacher` (`teacher_name`) VALUES ('Audrey');
INSERT INTO `teacher` (`teacher_name`) VALUES ('Sarah');
INSERT INTO `teacher` (`teacher_name`) VALUES ('Jacob');
INSERT INTO `teacher` (`teacher_name`) VALUES ('Jack');
INSERT INTO `teacher` (`teacher_name`) VALUES ('Luke');
INSERT INTO `teacher` (`teacher_name`) VALUES ('Anthony');
INSERT INTO `teacher` (`teacher_name`) VALUES ('Andrew');
INSERT INTO `teacher` (`teacher_name`) VALUES ('Adrian');
INSERT INTO `teacher` (`teacher_name`) VALUES ('George');
INSERT INTO `teacher` (`teacher_name`) VALUES ('Edward');

INSERT INTO `course` (`course_name`, `teacher_id`) VALUES ('Java - Fundamentals', '1');
INSERT INTO `course` (`course_name`, `teacher_id`) VALUES ('Java - Fundamentals: Coding', '2');
INSERT INTO `course` (`course_name`, `teacher_id`) VALUES ('Software Testing - Fundamentals', '3');
INSERT INTO `course` (`course_name`, `teacher_id`) VALUES ('Java - Advanced Features', '4');
INSERT INTO `course` (`course_name`, `teacher_id`) VALUES ('Design Patterns - Good Practices', '5');
INSERT INTO `course` (`course_name`, `teacher_id`) VALUES ('Java - Advanced Features: Coding', '6');
INSERT INTO `course` (`course_name`, `teacher_id`) VALUES ('Databases - SQL', '7');
INSERT INTO `course` (`course_name`, `teacher_id`) VALUES ('JDBC - Hibernate', '8');
INSERT INTO `course` (`course_name`, `teacher_id`) VALUES ('Practical Project', '9');
INSERT INTO `course` (`course_name`, `teacher_id`) VALUES ('Introduction to HTTP', '10');
INSERT INTO `course` (`course_name`, `teacher_id`) VALUES ('HTML. CSS. JavaScript', '11');
INSERT INTO `course` (`course_name`, `teacher_id`) VALUES ('Front-end Technologies', '12');
INSERT INTO `course` (`course_name`, `teacher_id`) VALUES ('Front-end Technologies & HTML. CSS. JavaScript', '13');
INSERT INTO `course` (`course_name`, `teacher_id`) VALUES ('Spring', '14');
INSERT INTO `course` (`course_name`, `teacher_id`) VALUES ('Software Testing - Advanced Features', '15');
INSERT INTO `course` (`course_name`, `teacher_id`) VALUES ('Agile. Scrum', '16');
INSERT INTO `course` (`course_name`, `teacher_id`) VALUES ('Cybersecurity and Blockchain', '1');
INSERT INTO `course` (`course_name`, `teacher_id`) VALUES ('IOT', '4');
INSERT INTO `course` (`course_name`, `teacher_id`) VALUES ('AI and Big Data', '6');
INSERT INTO `course` (`course_name`, `teacher_id`) VALUES ('Data Science and Analytics', '1');
INSERT INTO `course` (`course_name`, `teacher_id`) VALUES ('Robotics', '4');
INSERT INTO `course` (`course_name`, `teacher_id`) VALUES (' Pi Course - Raspberry Pi Foundation', '1');
INSERT INTO `course` (`course_name`, `teacher_id`) VALUES ('Python-Data-Structures', '4');
INSERT INTO `course` (`course_name`, `teacher_id`) VALUES ('Network and IT Security', '6');
INSERT INTO `course` (`course_name`, `teacher_id`) VALUES ('Artificial Intelligence', '4');
INSERT INTO `course` (`course_name`, `teacher_id`) VALUES ('Database', '13');
INSERT INTO `course` (`course_name`, `teacher_id`) VALUES ('HTML & CSS Course', '11');
INSERT INTO `course` (`course_name`, `teacher_id`) VALUES ('esponsive Web Design', '4');
INSERT INTO `course` (`course_name`, `teacher_id`) VALUES ('Word 2016', '9');
INSERT INTO `course` (`course_name`, `teacher_id`) VALUES ('Perl Specialist ', '1');

INSERT INTO `student_course` (`student_id`, `course_id`) VALUES ('2', '8');
INSERT INTO `student_course` (`student_id`, `course_id`) VALUES ('2', '2');
INSERT INTO `student_course` (`student_id`, `course_id`) VALUES ('4', '9');
INSERT INTO `student_course` (`student_id`, `course_id`) VALUES ('4', '6');
INSERT INTO `student_course` (`student_id`, `course_id`) VALUES ('4', '1');
INSERT INTO `student_course` (`student_id`, `course_id`) VALUES ('5', '9');
INSERT INTO `student_course` (`student_id`, `course_id`) VALUES ('5', '7');
INSERT INTO `student_course` (`student_id`, `course_id`) VALUES ('6', '8');