CREATE DATABASE IF NOT EXISTS jdbc_movies;
USE jdbc_movies;
CREATE TABLE IF NOT EXISTS MOVIES(
	id INTEGER AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(250),
    genre VARCHAR(250),
    yearOfRelease INT
);

DROP TABLE Movies;
DROP TABLE MOVIES;